### ISSUE TITLE
Modify GitHub Issue templates

### ISSUE THREAD

**Issue by kirillbobyrev** [kirillbobyrev/pabi#34]
For now, blank issues are allowed, but it would be better to offer some templates for most common issue types:

- [x] Bug (https://github.com/kirillbobyrev/pabi/pull/38)
- [ ] Feature request/Enhanement (https://github.com/kirillbobyrev/pabi/pull/40)

Maybe look for ideas in other repos/projects?

**Comment by RishiKumarRay** [comment]
I can work on this

**Comment by kirillbobyrev** [comment]
@RishiKumarRay That would definitely be helpful, thank you!

**Comment by RishiKumarRay** [comment]
Please review and merge , I am working on the 2nd template and soon generate other PR for that

**Comment by RishiKumarRay** [comment]
@kirillbobyrev I did all the changes please do review and let me know if there are more

**Comment by RishiKumarRay** [comment]
Thanks, So now I will work on other task and generate a PR soon.

**Comment by RishiKumarRay** [comment]
@kirillbobyrev I have generated PR #40 for feature template , Please do review

**Comment by RishiKumarRay** [comment]
@kirillbobyrev I have updated your suggestions please do review and let me know if there are more

**Comment by RishiKumarRay** [comment]
Now you can disable blank issue and its good to go.

**Comment by kirillbobyrev** [comment]
> Now you can disable blank issue and its good to go.

Good point! I think, I'll just leave it for now just in case and if I don't see any blank issues in the future, I'll just disallow them. Thanks again!

**Comment by RishiKumarRay** [comment]
@kirillbobyrev I was thinking of adding a greetings bot that will greet every one with custom message whenever a new issue or PR is created , What do you think?

**Comment by kirillbobyrev** [comment]
@RishiKumarRay frankly speaking, at this point the project is not in a functional state (yet, actively working on it) and there are no PRs. Issue templates make sense to me because there is at least one user for those (me); PR templates might make sense but I don't know how those (at least the majority) would look like, so I don't think that would be important right now.
