### ISSUE TITLE
Use thiserror and anyhow

### ISSUE THREAD

**Issue by kirillbobyrev** [kirillbobyrev/pabi#35]
[thiserror](https://github.com/dtolnay/thiserror) and [anyhow](https://github.com/dtolnay/anyhow) are idiomatic ways to handle errors in Rust, I should consider migrating to them instead of the plain Rust error mechanism.

**Comment by RishiKumarRay** [comment]
Hi added the First file of Bug Template #38 
Please review

**Comment by RishiKumarRay** [comment]
Similarly i adding one more template of feature in another PR

**Comment by kirillbobyrev** [comment]
For now, `anyhow` should be enough. Once and if I'm going to create a set of specific errors that have to be handled separately, I would use `thiserror`, too.
