### ISSUE TITLE
Make script for running the whole pipeline to ensure that the code change is valid

### ISSUE THREAD

**Issue by kirillbobyrev** [kirillbobyrev/pabi#58]
### Description

When changes are made, they should be tested for correctness and performance. Right now, there are few commands to run all these and it can quickly get forgotten/missed (e.g. some tests are ignored). It would be cool to have some script running all these before submitting a change/for gradual refactoring validation. Ideally, that could be a cargo "target" or command but I don't really remember if there is anything like that in cargo.

The commands I typically run are:

- `cargo test`
- `cargo test --ignored`
- `cargo bench --profile=fast`
- `cargo +nighty fuzz run <target>`, probably best with a reasonable timeout

Maybe there would be more in the future (e.g. `typos`, something else).

**Comment by RishiKumarRay** [comment]
do we have to make github actions?

**Comment by kirillbobyrev** [comment]
I think the GH Actions would be nice to verify that the script can be executed correctly and won't fail, but my main incentive is to make something for myself to avoid relying on muscle memory and typing all these commands myself. It's more of a "the checks I'm running in CI but running locally before sending the patch" or when iterating in a refactoring change.

**Comment by kirillbobyrev** [comment]
Done in https://github.com/kirillbobyrev/pabi/commit/199b558258fdc19977c55c95afd51fbd80c9aef5
